TYPO3:
  TYPO3CR:

    # Configure available content dimensions for nodes, after adding a dimension the database has to be filled with
    # the dimension default values.
    # Also add named presets with fallback chains that can happen in your dimensions.
    #
    # Example
    #
    #   contentDimensions:
    #     language:
    #       default: mul_ZZ
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['mul_ZZ']
    #
    #     persona:
    #       default: everybody
    #       defaultPreset: 'all'
    #       presets:
    #         'all':
    #           values: ['everybody']
    contentDimensions: []

    # Configures defaults for node label generation
    labelGenerator:
      eel:
        defaultContext:
          String: 'TYPO3\Eel\Helper\StringHelper'
          Array: 'TYPO3\Eel\Helper\ArrayHelper'
          Date: 'TYPO3\Eel\Helper\DateHelper'
          Configuration: 'TYPO3\Eel\Helper\ConfigurationHelper'
          Math: 'TYPO3\Eel\Helper\MathHelper'
          Json: 'TYPO3\Eel\Helper\JsonHelper'

  Flow:
     # disable reflection for non psr-0 compliant 3rd party packages
    object:
      excludeClasses:
       'gedmo.doctrineextensions' : ['Gedmo\\.*']
       'Behat.Transliterator' : ['Behat\\Transliterator\\.*']

     # register soft deletable filter & event listeners
    persistence:
      doctrine:
        eventListeners:
          'Gedmo\Timestampable\TimestampableListener':
            events: ['prePersist', 'onFlush', 'loadClassMetadata']
            listener: 'Gedmo\Timestampable\TimestampableListener'